### ISSUE TITLE
Cathy Le (SEI28): Project 4

### ISSUE THREAD

**Issue by Cathy347Le** [ga-dc/sei-project4-gallery#24]
Student Name: Cathy Le

Project Name: Recreating a 2018 Senate Elections Site

Link github repo(s): https://github.com/Cathy347Le/2018-Senate-Election-Site

Link to deployed version: http://project-5-election-site.surge.sh/

Feedback: I put all my css in style.css - is that a good or bad idea?

**Comment by tomatohammado** [comment]
AWESOME project!!! This is a very cool concept and you did an awesome job with the layout and visualizations.

To answer your question we generally condense all of the CSS into a single stylesheet during the build process, because that is easier to minify and transmit to the client. However, it is a little easier to develop when there are small, clear CSS files for each component. Separate files also helps reconcile merge conflicts in larger projects as well.

Great work!
